<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Compaq510" ignored="0" name="Test(failed)" tests="3" failures="3" timestamp="2021-06-04T02:02:37 IST" time="29.705" errors="0">
  <testcase name="loginDDT" time="7.261" classname="com.inetBanking.Testcases.TC002_LoginTest_DataProvider">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.Testcases.TC002_LoginTest_DataProvider.loginDDT(TC002_LoginTest_DataProvider.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="5.473" classname="com.inetBanking.Testcases.TC002_LoginTest_DataProvider">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.Testcases.TC002_LoginTest_DataProvider.loginDDT(TC002_LoginTest_DataProvider.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="6.74" classname="com.inetBanking.Testcases.TC002_LoginTest_DataProvider">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.Testcases.TC002_LoginTest_DataProvider.loginDDT(TC002_LoginTest_DataProvider.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- Test(failed) -->
